# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField()),
                ('account_type', models.CharField(choices=[('F', 'F\xedsica'), ('J', 'Jur\xeddica')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Account')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Account')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=250)),
                ('cardid', models.IntegerField()),
            ],
        ),
    ]
